blank_issues_enabled: false
contact_links:
  - name: Question or usage help
    url: https://github.com/xmaiconx/add-commands-scripts/discussions
    about: Please ask and answer questions in Discussions.

